.github/workflows/tests.yml, CHANGES.rst, README.rst, tests/conftest.py, tests/docker-compose.yml
What the title says. The patch will make the test suite on CI run against Grafana versions 6.7.6, 7.5.10 and 8.1.5.
=> Run tests on CI against different versions of Grafana

CHANGES.rst, grafana_wtf/commands.py, grafana_wtf/core.py, grafana_wtf/model.py, grafana_wtf/util.py, setup.py, tests/conftest.py, tests/test_commands.py
Hi there,
this feature can specifically be used to find unused data sources. The topic has been brought up by @chenlujjj at [1], thanks!
```shell
export GRAFANA_URL=https://grafana.example.org/
grafana-wtf datasource-breakdown --format=json | jq -r '.unused[].datasource.name'
```
Andreas.
[1] https://community.grafana.com/t/how-to-find-out-unused-datasources/56920
=> Add feature to display datasource breakdown

CHANGES.rst, README.rst, doc/backlog.rst, grafana_wtf/commands.py, grafana_wtf/core.py, grafana_wtf/model.py, tests/conftest.py, tests/test_commands.py
Hi again,
this patch will add the `grafana-wtf info` subcommand. It will display the Grafana version and _global statistics_ about many entities. Please let me know you if you are missing anything important. _Per-entity statistics_ will be tackled with #18.
Data for the `statistics` slot is coming from Grafana's `/admin/stats` endpoint. Data for the `summary` slot is computed by `grafana-wtf` itself.
Andreas.
/cc @jangaraj
```shell
$ grafana-wtf info --format=yaml
```
```yaml
grafana:
version: 8.3.2
url: http://localhost:3000
statistics:
activeAdmins: 1
activeEditors: 0
activeSessions: 0
activeUsers: 1
activeViewers: 0
admins: 1
alerts: 0
dailyActiveAdmins: 0
dailyActiveEditors: 0
dailyActiveSessions: 0
dailyActiveUsers: 1
dailyActiveViewers: 0
dashboards: 1 …
```
=> Add subcommand `info`

.dockerignore, .github/workflows/release-docker.yml, CHANGES.rst, Dockerfile, README.rst, doc/backlog.rst
Some users might prefer to run `grafana-wtf` in cloud environments or don't want to fuzz with the installation on Python.
```shell
docker run --rm -it --env GRAFANA_URL="http://host.docker.internal:3000" ghcr.io/panodata/grafana-wtf grafana-wtf log
docker run --rm -it --env GRAFANA_URL="https://daq.grafana.org/grafana" --env GRAFANA_TOKEN="eyJrIjoiWHg...dGJpZCI6MX0=" ghcr.io/panodata/grafana-wtf grafana-wtf log
```
=> Add `Dockerfile` and GHA recipe to publish container images to GHCR

.github/workflows/tests.yml, grafana_wtf/commands.py
- CI: Use most recent Grafana 8.3.3.
- Add two more examples about using explore dashboards with jq.
- Display all dashboards which use a specific data source, by name.
- Display all dashboards using data sources with a specific type.
=> Minor updates

CHANGES.rst, grafana_wtf/core.py, grafana_wtf/monkey.py, setup.py, tests/conftest.py
Hi.
This patch makes `grafana-wtf` compatible with the `grafana-client` library fork, see https://github.com/m0nhawk/grafana_api/issues/88.
Andreas.
=> Switch to the `grafana-client` library fork

CHANGES.rst, doc/backlog.rst, grafana_wtf/commands.py, grafana_wtf/core.py, setup.py, tests/conftest.py, tests/test_commands.py
This patch does a few things.
- Tests: Improve test quality, specifically for `explore dashboards`.
Grafana 6 vs. Grafana >= 7 have a different behaviour here because Grafana 6 did not know about data source UIDs yet.
- Tests: Make test case for `explore datasources` use _two_ data sources.
- Tests: Mimic Grafana 7/8 on datasource references within dashboards.
Newer versions have objects (uid, type) instead of bare names. This improvement reveals an implementation flaw.
- Fix implementation flaw with 6e3b440efb.
Kudos to @IgorOhrimenko and @carpenterbees for reporting this bug at #32.
=> Improve tests and fix implementation flaw

.github/workflows/tests.yml, CHANGES.rst, README.rst
What the title says.
Edit: What a coincidence. Grafana 9 has been released just some minutes ago.
=> CI: Use most recent Grafana 7.5.16, 8.5.5, and 9.0.0

CHANGES.rst, grafana_wtf/core.py, tests/conftest.py, tests/test_commands.py
Hi there,
@TaylorMutch reported at #36 that `grafana-wtf explore dashboards` croaks for him.
> It looks like one of the dashboards you are requesting has an **unassigned** `annotations` slot, i.e. its value equals `None`. The code probably expects it to be an **empty list** instead. 
After looking into this, we found that was exactly the case. This patch makes the gathering process more graceful to compensate for such a situation.
Andreas.
=> Fix dashboard exploration when the `annotations.list` slot is `None`

Dockerfile, requirements-release.txt, setup.py
Fix for:
```
#18 6.574 error: urllib3 2.0.0a1 is installed but urllib3<1.27,>=1.21.1 is required by {'requests'}
```
-- https://github.com/panodata/grafana-wtf/actions/runs/3478374517/jobs/5815665994#step:10:597
=> CI: Fix `release-docker` workflow

CHANGES.rst, grafana_wtf/report.py, grafana_wtf/util.py, tests/test_commands.py
This patch adds direct URLs to dashboard variables (`editview=templating`), and to panel view/edit pages (`viewPanel=`, `editPanel=`) to the output of the "find" subcommand, as requested by @oplehto at GH-43.
=> Add URLs to dashboard variables and panel view/edit pages to the output of the "find" subcommand

.github/workflows/tests.yml, .gitignore, CHANGES.rst, doc/backlog.rst, grafana_wtf/commands.py, grafana_wtf/core.py, setup.py
- Improve display of progressbar wrt. being interrupted by logging output: 5bd006f34
- Improve caching: 9bf1f65677
- Use cache database location within user folder
- Send cache database location to log
- Reduce default cache TTL from five minutes to 60 seconds
- Because of the dependency to a more recent `requests-cache` package, this patch also drops support for Python 3.6.
=> Modernize caching and progressbar, and drop support for Python 3.6

.github/workflows/release-docker.yml
Make this an even better blueprint for copying to other repositories.
=> CI: Generalize GHA recipe for building and publishing Docker images

CHANGES.rst, grafana_wtf/core.py, grafana_wtf/util.py, tests/test_core.py
Dear @mauhiz,
this patch may fix the issue you reported at GH-62. The machinery croaked on `"value": ["$__all"]` when finding a templated datasource within a dashboard representation. Because `$__all` will not resolve to a specific data source, this item will get skipped now, but a warning will be emitted.
Thank you very much for your valuable hints about the origin of the problem.
Andreas.
=> Fix `collect_datasource_items` when hitting special templated datasource

CHANGES.rst, grafana_wtf/commands.py, grafana_wtf/core.py, grafana_wtf/report/data.py, grafana_wtf/report/tabular.py, grafana_wtf/report/textual.py, tests/conftest.py, tests/test_commands.py
- Explore dashboards: Ignore ``-- Mixed --`` data sources
- Caching: Increase default cache TTL to five minutes again
- Caching: Optionally configure TTL using environment variable ``CACHE_TTL``
- History: Stop ``grafana-wtf log <UID>`` acquiring *all* dashboards
- Refactoring: Move all report renderers to ``grafana_wtf.report``
- History: Add ``id`` and ``uid`` dashboard attributes to report
- History: Unlock YAML export format
- History: Add new options ``--head``, ``--tail``, and ``--reverse``
- Search: Unlock JSON and YAML export formats
=> A few changes across the board

CHANGES.rst, Dockerfile, grafana_wtf/commands.py, grafana_wtf/util.py, setup.py, tests/test_commands.py
Hi there,
at Hiveeyes, we needed to discover all Grafana dashboards with only a single edit, i.e. without any further activity.
With this patch, adding SQL querying capabilities to the dashboard version history, it is very easy, thanks to pandas and DuckDB [^1].
```sql
SELECT uid, url, COUNT(version) as number_of_edits
FROM dashboard_versions
GROUP BY uid, url
HAVING number_of_edits=1
```
Andreas.
[^1]: While this example does not emphasize DuckDB's performance characteristics, it is a perfect showcase example how convenient it is to add SQL querying capabilities to data on the library level.
/cc @jangaraj, @hannes, @mytherin
=> History: Add SQL querying capabilities

.github/workflows/oci.yml
The OCI image build machinery can't upload to GHCR when running on behalf of non-members.
- https://github.com/earthobservations/wetterdienst/pull/967
- https://github.com/daq-tools/lorrystream/pull/19
=> CI: Do not build and publish OCI images on GHA PRs from non-members

grafana_wtf/report/textual.py
Hi @amotl,
this fixes https://github.com/panodata/grafana-wtf/issues/66.
The issue was happening because panels don't necessarily always have a title, therefore it was causing `AttributeError`.
Best regards,
Nikodemas
=> Fix empty title issue

CHANGES.rst, grafana_wtf/core.py
This patch implements the suggestion by @meyerder at GH-70. When finding unused datasources, ignore a few more dashboard names.
=> Improve finding unused datasources

grafana_wtf/core.py
Original file name is `http_cache.sqlite` which makes it hard to know who owns the file in `$XDG_CACHE_HOME`.
This sets it to the application name.
=> Caching: Set cache filename to appname

CHANGES.rst, README.rst, grafana_wtf/commands.py, grafana_wtf/core.py, grafana_wtf/util.py, setup.py, tests/conftest.py, tests/test_commands.py
At https://github.com/panodata/grafana-client/pull/110, @bhks added a few more API wrapper functions for Grafana. Thanks! This patch wraps them once more into the command line interface of grafana-wtf.
```
grafana-wtf plugins list
grafana-wtf plugins status
```
=> Add subcommands `plugins {list,status}`, to inquire plugins

CHANGES.rst, README.rst, grafana_wtf/commands.py, grafana_wtf/core.py, setup.py, tests/conftest.py, tests/test_commands.py
GH-91 was integrated into the wrong branch, due to a PR stacking mistake, apologies. This fixes it.
=> Add subcommands `plugins {list,status}`, to inquire plugins - now for real

tests/test_commands.py
```
FAILED tests/test_commands.py::test_log_filter_sql
```
-- https://github.com/panodata/grafana-wtf/actions/runs/6767493651/job/18390219379#step:5:246
- Blocks GH-107
=> Fix flaky test case `test_log_filter_sql`

grafana_wtf/report/textual.py
I noticed that there is a bug in the textual output as data sources get a prefix of `Dashboard` instead of `Data Source`, because `Dashboard` is hard-coded.
https://github.com/panodata/grafana-wtf/pull/106 can be closed without merging.
=> Fix datasource output text

.github/workflows/tests.yml, CHANGES.rst, Makefile, setup.py
Add Python 3.12 to CI.
- https://github.com/numpy/numpy/issues/23808#issuecomment-1676838801
- https://github.com/duckdb/duckdb/issues/9301#issuecomment-1756731027
- https://github.com/duckdb/duckdb/pull/9222
=> Add support for Python 3.12

.github/workflows/oci.yml, .github/workflows/tests.yml, .gitignore, CHANGES.rst, README.rst, pyproject.toml, setup.py
- Add support for Python 3.12
- Remove support for Python 3.7
- Tests: Report code coverage
- Documentation: Adjust badges in README, GitHub changed the rST rendering
=> More Maintenance

CHANGES.rst, grafana_wtf/__init__.py, grafana_wtf/compat.py, grafana_wtf/core.py
- @JensRichnow recently reported problems with concurrency on fast / highly concurrent machines, like the Apple M2 Max.
- GH-111
- @JWCook suggested to use `requests_cache.CachedSession` to improve the situation.
- https://github.com/requests-cache/requests-cache/issues/870#issuecomment-1716370826
- https://github.com/panodata/grafana-wtf/issues/111#issuecomment-1837550141
- This patch aims to do just that. Thank you very much!
Users on Apple M2 Max reported DB lock errors:
```log
[grafana_wtf.core]
INFO: Fetching dashboards in parallel with 5 concurrent requests
[requests_cache.backends.sqlite]
WARNING: Database is locked in thread 6272069632; retrying (1/3)
```
Also segmentation faults, and leaks:
```log
UserWarning: resource_tracker: There appear to be 1 leaked semaphore
objects to …
```
=> SQLite cache: Use `requests_cache.CachedSession` for better concurrency

CHANGES.rst, grafana_wtf/commands.py, grafana_wtf/core.py, tests/conftest.py, tests/test_core.py
Improve robustness when connecting, based on reports by @interfan7 at GH-113. 🙇 
- Rework "health" method (now a property) to raise exception on errors
- Report Grafana version on startup
- Improve error messages
- Add software tests evaluating connectivity error handling
=> Improve error reporting on invalid Grafana URLs, or invalid endpoints

CHANGES.rst, doc/backlog.rst, grafana_wtf/core.py, setup.py
=> Chore: A bit more maintenance

.gitignore, doc/backlog.rst, grafana_wtf/__init__.py, grafana_wtf/commands.py, grafana_wtf/compat.py, grafana_wtf/core.py, grafana_wtf/util.py, tests/conftest.py, tests/test_core.py
That other patch did not get everything right wrt. proper caching. This one fixes it, applying suggestions by @Ousret. Thanks!
- https://github.com/panodata/grafana-wtf/pull/130#discussion_r1545547301
=> Fix caching after migration to Niquests

CHANGES.rst, grafana_wtf/core.py
@edgarasg reported there is still a problem with the SQLite-based cache and concurrent access.
- https://github.com/panodata/grafana-wtf/issues/111#issuecomment-2058840165
@JWCook informed us about the `wal=True` argument to requests-cache' Session class/mixin, effectively enabling [SQLite write-ahead logging](https://sqlite.org/wal.html), allowing read operations to not block writes.
- https://github.com/panodata/grafana-wtf/issues/111#issuecomment-2067705159
[1] https://sqlite.org/wal.html
=> SQLite cache: Use SQLite write-ahead logging for better concurrency

grafana_wtf/core.py, tests/test_core.py
AWS-managed Grafana API doesn't contain `/api/health` endpoint, which makes it impossible to use `grafana-wtf` with this kind of setup.
The proposal is to use `/api/frontend/settings` for the same purpose, which works for both regular and AWS-managed Grafana versions.
Fixes https://github.com/grafana-toolbox/grafana-wtf/issues/141
=> Fetch Grafana version from `/api/frontend/settings`

Makefile, setup.py
- The v1 `docker-compose` command no longer exists on contemporary environments.
- GH-143 fails to conclude, because it errors out trying to use `docker-compose`.
=> CI: Update dependencies for Docker-based test layer

CHANGES.rst, grafana_wtf/model.py, tests/test_model.py
Dear @apepojken. This patch intends to poke at the details based on your report.
- GH-110
> When I try to explore datasources it always fail with a TypeError.
> No idea why this happens.
Exception:
```python
TypeError: DatasourceItem.__init__() got an unexpected keyword argument 'datasource'
```
It is unlikely that this is the correct fix. It hasn't been validated in any way, so it is purely based on guessing, not even educated. We will ask a few more questions at GH-110.
=> Accept `datasource` attribute on `DatasourceItem`, but ignore it

.github/workflows/tests.yml, CHANGES.rst, setup.py
[Python 3.13.0](https://www.python.org/downloads/release/python-3130/) has been released on Oct. 7, 2024. This PR intends to add CI verification.
- https://github.com/grafana-toolbox/grafana-client/pull/192
- https://github.com/crate/crate-python/pull/653
=> CI: Verify support on Python 3.13

Makefile
A little modernization, preparing to phase out `setup.py`.
```
/home/runner/work/grafana-wtf/grafana-wtf/.venv/lib/python3.13/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
/home/runner/work/grafana-wtf/grafana-wtf/.venv/lib/python3.13/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!
********************************************************************************
Please avoid running ``setup.py`` directly.
Instead, use pypa/build, pypa/installer or other
standards-based tools.
See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
********************************************************************************
!!
```
- …
=> CI+Sandbox: Stop using `setup.py`, instead only use `pip`

Dockerfile
Further improve the OCI (building).
- [Trim total cold run time, by also using slim-bookworm for build](https://github.com/grafana-toolbox/grafana-wtf/commit/b1827e5e2d607eec1cd6f818bcbf5d536d5d6f05)
- [Serve grafana-wtf program per symlink instead of adjusting $PATH](https://github.com/grafana-toolbox/grafana-wtf/commit/93fc4f8ff53766472204cba08ce66291acaf7104)
=> OCI: Improve building

CHANGES.rst, grafana_wtf/model.py
Compensate for a dashboard that apparently trips processing, as reported by @jwoodhouse. Thanks!
- https://github.com/grafana-toolbox/grafana-wtf/issues/150
Is it the right fix? / Is the fix right?
/cc @sanadhis, @rlauzon-ea
=> Fix `DatasourceItem` re. `Unexpected keyword argument 'default'`

grafana_wtf/commands.py, grafana_wtf/core.py
Hi @amotl,
I again felt the need of seeing in what dashboards different notification channels are used as previously described by me in https://github.com/grafana-toolbox/grafana-wtf/issues/82, so I updated the code to satisfy my needs. However, there are some things worth mentioning:
* this only searches through alerts that were created before Grafana 8, because after this alerting stopped being tied to the panel/dashboard, so this information is not available anymore. The command doesn't break on occasions like this, it just doesn't return any information about the related panels.
* even then the structure of the alert information differs slightly between the dashboards, hence my update includes the sketchy `if-elif`
* if you still think that this is something useful for the …
=> Update channel scanning

grafana_wtf/core.py
This PR fixes a bug where datasources that were being used in dashboards through variables were being wrongly categorised as unused (in `explore datasources`) and missing (in `explore dashboards`).
The full description of the problem can be seen in the issue #164 along with steps to reproduce it.
=> fix: variable datasources shown as missing and unused datasource

Makefile, grafana_wtf/commands.py, grafana_wtf/core.py, grafana_wtf/model.py, grafana_wtf/report/data.py, grafana_wtf/report/tabular.py, grafana_wtf/report/textual.py, grafana_wtf/util.py, pyproject.toml, requirements-release.txt, setup.py, tests/conftest.py, tests/test_commands.py, tests/test_core.py
=> Chore: Format code using Ruff

.github/workflows/tests.yml
=> CI: Do not cache packages twice, per pip and uv. Just cache with uv.

setup.py
Hi @amotl,
I wasn't able to run `grafana-wtf` with the `verlib2 0.3.0`, so I think this change should prevent this problem.
=> Update verlib2 version requirement

CHANGES.rst, grafana_wtf/core.py, tests/test_commands.py
Users reported about errors without this patch, see references.
- GH-190
- GH-191
=> Fix 404 error on "dash-folder" dashboard type

CHANGES.rst, grafana_wtf/core.py
When data sources are defined by dashboard variables, a ton of warnings like `Data source 'datasource-3' not found` are emitted.
It looks like resolving this bit of information beared a programming error.
@cronosnull [suggested](https://github.com/grafana-toolbox/grafana-wtf/issues/187#issuecomment-2866458945) an excellent improvement. Thanks!
> I think the values in the variables are data source names, but not completely sure, so I would support both cases.
=> Fix collecting data sources defined by dashboard variables
